import {inter, kanit} from './ui/fonts'
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${kanit.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
